BeratTelur = (5)
HargaTelur = (26000)
Ongkos = (3500)
UangIbu = (200000)
TotalTelur = (BeratTelur * HargaTelur)
OngkosPp = (Ongkos + Ongkos)
SisaUangIbu = (UangIbu - (TotalTelur + OngkosPp))
print(SisaUangIbu)